### ISSUE TITLE
Ignore typing.cast

### ISSUE THREAD

**Issue by cleder** [isac322/flake8-force-keyword-arguments#11]
In a type annotated codebase that uses a lot of casting to make `mypy` happy I get a lot of
` FKA100 cast's call uses 2 positional arguments, use keyword arguments.`
can this be ignored by default?

`flake8 directory --kwargs-ignore-function-pattern-extend='^cast$'`
works fine

**Comment by isac322** [comment]
@cleder Thanks for issuing.

It turns out `cast` is not a positional-only function.
```
>>> from typing import cast
>>> cast(typ=int, val=1)
1
```

But since no one uses `cast` with keyword, it makes sense to add it to the default exclusion list.

**Comment by isac322** [comment]
@cleder 1.0.4 is released!
